# Rest file to be used with vim-rest-console
# https://github.com/diepm/vim-rest-console

# Login as Bob
https://dev.local
--connect-timeout 10
--max-time 60
--ipv4
-c /tmp/cookie.jar
-b /tmp/cookie.jar
-L
-i
Content-Type: application/json; charset=utf-8
POST /api/users/login
{
  "email":"bob@example.com",
  "password":"test1234"
}

# Logout
https://dev.local
--connect-timeout 10
--max-time 60
--ipv4
-c /tmp/cookie.jar
-b /tmp/cookie.jar
-L
-i
POST /api/users/logout

# Get Bob's name
https://dev.local
--connect-timeout 10
--max-time 60
--ipv4
-c /tmp/cookie.jar
-b /tmp/cookie.jar
-L
-i
GET /api/users/68b1d5e2-39dd-4713-8631-a08100383a0f/name

# Get a list of patients
https://dev.local
--connect-timeout 10
--max-time 60
--ipv4
-c /tmp/cookie.jar
-b /tmp/cookie.jar
-L
-i
GET /api/patients
